export const CONCERN_LIST = [
  {
    id: 1,
    title: "고민1",
    content: "앞길이 막막해요..",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    writer: "mung5079",
  },
  {
    id: 2,
    title: "고민2",
    content: "앞길이 막막해요..",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    writer: "mung5079",
  },
  {
    id: 3,
    title: "고민3",
    content: "앞길이 막막해요..",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    writer: "mung5079",
  },
  {
    id: 4,
    title: "고민4",
    content: "앞길이 막막해요..",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    writer: "mung5079",
  },
  {
    id: 5,
    title: "고민5",
    content: "앞길이 막막해요..",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    writer: "mung5079",
  },
];
