export const QNA_LIST = [
  {
    id: 1,
    title: "질문1",
    content: "이거 뭔가연?하나도 모르겠네요...",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    lecture: "공카데미",
    course: "리액트",
    writer: "mung5079",
  },
  {
    id: 2,
    title: "질문2",
    content: "이거 뭔가연?하나도 모르겠네요...",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    lecture: "공카데미",
    course: "리액트",
    writer: "mung5079",
  },
  {
    id: 3,
    title: "질문3",
    content: "이거 뭔가연?하나도 모르겠네요...",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    lecture: "공카데미",
    course: "리액트",
    writer: "mung5079",
  },
  {
    id: 4,
    title: "질문4",
    content: "이거 뭔가연?하나도 모르겠네요...",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    lecture: "공카데미",
    course: "리액트",
    writer: "mung5079",
  },
  {
    id: 5,
    title: "질문5",
    content: "이거 뭔가연?하나도 모르겠네요...",
    date: "2022년 5월 13일",
    like: 1,
    viewCnt: 10,
    scrap: false,
    lecture: "공카데미",
    course: "리액트",
    writer: "mung5079",
  },
];
